Add Support for Encoding in PBES2
SSLMate/go-pkcs12 pull request #47
Opened 2023-05-29 02:28 UTC by Tookmund

With the release of OpenSSL v3, openssl now defaults to "AES password based encryption (PBES2 with PBKDF2 and AES-256-CBC) for private keys and certificates, the PBKDF2 and MAC key derivation iteration count of PKCS12_DEFAULT_ITER (currently 2048), and MAC algorithm HMAC with SHA2-256."
https://www.openssl.org/docs/man3.0/man3/PKCS12_create.html
All other formats are now considered legacy.

This PR builds on the configuration work done in #39 , simply adding support for PBES2 as an algorithm choice.
This doesn't support encoding in every algorithm that could be used for PBES2, but only the exact format used by OpenSSL.
Other formats are left as a future enhancement, and will likely require a rethink of the interface used to select algorithms in #39.

Additionally this solves #44 by bumping the `x/crypto` dependency to `0.9.0`. This appears to work without any changes required.

2023-05-31 01:00 UTC, maraino requested changes
I haven't looked at the full PR, only at the KDF parameters. I am not a go-pkcs12 mainteiner.

2023-06-30 23:17 UTC, Tookmund commented on safebags.go
> +	if _, err = rand.Read(iv); err != nil {
Thanks! I've found a number of places where we read from rand without checking and corrected them all to this construction.

2023-07-04 02:37 UTC, Tookmund commented
I've defaulted to 2048 in most places, since that's still what OpenSSL uses, but I've increased SafeEncode to the standard 600,000 iterations.

2023-07-15 00:56 UTC, Tookmund commented
Closed in favor of #48

2023-07-15 00:56 UTC, closed without merging